export const teacherTitle='Pro učitelé';
export const orderTitle = 'Objednávka pro MŠ/ZŠ'
export const icoValue = "22834958";
export const wrongIcoValue = "228358";
export const messageValue = "Data z ARESu úspěšně načtena";
export const messageForWrongIco = "IČO nenalezeno, zkontrolujte jej prosím";
export const clientNameValue = "Czechitas z.ú.";
export const adressValue = "Václavské náměstí 837, 11000 Praha";
export const substituteValue = "Jan Novak";
export const contactTelValue = "+420792387111";
export const wrongTelValue = "4207923871115";
export const contactMailValue = "jannovak010@seznam.cz";
export const startDate1Value = '01.01.2022';
export const endDate1Value = '30.01.2022';
export const campStudentsValue = '15';
export const campAgeValue = '8';
export const campAdultsValue = '3';
export const orderOkText = 'Objednávka byla úspěšně uložena';
//export const missingInputMsg = 'Některé pole obsahuje špatně zadanou hodnotu'